on:
  push:
    branches:
      - main

name: Release Tag

jobs:
  release:
    runs-on: ubuntu-latest
    name: Create Release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release
        uses: ./
        id: release-action
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
